version: '3.9'
services:
  stoq:
    image: faelp22/stoq:1.0.1
    # restart: always
    environment:
      - SRV_WEB_UI=false
      - SRV_MODE="developer"

    ports:
      - 8080

    labels:
      - "msgateway.name=autenticacao"
      - "msgateway.path=/"
      - "msgateway.jwt_check=false"
      - "msgateway.db_auto=false"
