srv_port = '8080'
web_ui = false
mode = 'production'
[dbconfig]
# db_drive = 'sqlite3'
# db_name = 'db.sqlite3'
db_drive = 'postgres'
db_host = '192.168.18.2'
db_port = '5432'
db_user = 'postgres'
db_pass = '123456'
db_name = 'stoq'
